# Generated by Django 5.1.2 on 2024-11-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoShootTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpotName', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('EntryTime', models.DateTimeField(blank=True, null=True)),
                ('ExitTime', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResortTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResortName', models.CharField(blank=True, max_length=30, null=True)),
                ('OwnerName', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaourantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantName', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TuristTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResortOfferTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferName', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('StartingTime', models.DateTimeField(blank=True, null=True)),
                ('endingTime', models.DateTimeField(blank=True, null=True)),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.resorttable')),
            ],
        ),
        migrations.CreateModel(
            name='ResortMenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.resorttable')),
            ],
        ),
        migrations.CreateModel(
            name='ResortGalleryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Features', models.CharField(blank=True, max_length=500, null=True)),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.resorttable')),
            ],
        ),
        migrations.CreateModel(
            name='ResortFacilityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility', models.CharField(blank=True, max_length=300, null=True)),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Status', models.CharField(blank=True, max_length=500, null=True)),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.resorttable')),
            ],
        ),
        migrations.CreateModel(
            name='ResortDescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History', models.CharField(blank=True, max_length=500, null=True)),
                ('Features', models.CharField(blank=True, max_length=500, null=True)),
                ('RESORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.resorttable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History', models.CharField(blank=True, max_length=500, null=True)),
                ('Features', models.CharField(blank=True, max_length=500, null=True)),
                ('RESTAURANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.restaouranttable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFacilityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility', models.CharField(blank=True, max_length=300, null=True)),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Status', models.CharField(blank=True, max_length=500, null=True)),
                ('RESTAURANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.restaouranttable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantGalleryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Features', models.CharField(blank=True, max_length=500, null=True)),
                ('RESTAURANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.restaouranttable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('RESTAURANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.restaouranttable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOfferTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferName', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('StartingTime', models.DateTimeField(blank=True, null=True)),
                ('endingTime', models.DateTimeField(blank=True, null=True)),
                ('RESTAURANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.restaouranttable')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSoptTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(blank=True, max_length=30, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('NoParking', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('TURIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.turisttable')),
            ],
        ),
        migrations.CreateModel(
            name='FestivelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FestivelName', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('StartingTime', models.DateTimeField(blank=True, null=True)),
                ('endingTime', models.DateTimeField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('TURIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.turisttable')),
            ],
        ),
        migrations.CreateModel(
            name='AmalgamationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Place', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('TURIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.turisttable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Reply', models.CharField(blank=True, max_length=300, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPointTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViewPoint', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('TURIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.turisttable')),
            ],
        ),
    ]
