# Generated by Django 5.1.2 on 2024-11-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0005_rename_turisttable_touristtable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingSoptTable',
            new_name='ParkingSpotTable',
        ),
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.CharField(choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('RESORT', 'resort'), ('USER', 'user'), ('ADMIN', 'admin'), ('TOURIST', 'tourist'), ('RESTOURANT', 'restaurant')], max_length=20, null=True),
        ),
    ]
