# Generated by Django 5.1.2 on 2024-11-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0007_photoshoottable_tourist_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('RESTOURANT', 'restaurant'), ('TOURIST', 'tourist'), ('USER', 'user'), ('RESORT', 'resort'), ('ADMIN', 'admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photoshoottable',
            name='EntryTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoshoottable',
            name='ExitTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
