# Generated by Django 5.1.2 on 2024-11-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0010_remove_logintable_status_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('RESORT', 'resort'), ('RESTOURANT', 'restaurant'), ('USER', 'user'), ('ADMIN', 'admin'), ('TOURIST', 'tourist')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ResortRatingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRatingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
    ]
