# Generated by Django 5.1.2 on 2024-11-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0011_alter_logintable_user_type_resortratingtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortratingtable',
            name='RESORT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SportComApp.resorttable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantratingtable',
            name='RESTAURANT',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='SportComApp.restauranttable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('RESTOURANT', 'restaurant'), ('RESORT', 'resort'), ('ADMIN', 'admin'), ('TOURIST', 'tourist'), ('USER', 'user')], max_length=20, null=True),
        ),
    ]
