# Generated by Django 5.1.2 on 2024-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0013_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('USER', 'user'), ('RESORT', 'resort'), ('RESTOURANT', 'restaurant'), ('TOURIST', 'tourist'), ('ADMIN', 'admin')], max_length=20, null=True),
        ),
    ]
