# Generated by Django 5.1.2 on 2024-11-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0014_alter_logintable_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FestivelTable',
            new_name='FestivalTable',
        ),
        migrations.RenameField(
            model_name='festivaltable',
            old_name='FestivelName',
            new_name='FestivalName',
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('USER', 'user'), ('RESORT', 'resort'), ('RESTOURANT', 'restaurant'), ('ADMIN', 'admin'), ('TOURIST', 'tourist')], max_length=20, null=True),
        ),
    ]
