# Generated by Django 5.1.2 on 2024-11-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0015_rename_festiveltable_festivaltable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('USER', 'user'), ('RESORT', 'resort'), ('ADMIN', 'admin'), ('RESTOURANT', 'restaurant'), ('TOURIST', 'tourist')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FestivalRatingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('FESTIVAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.festivaltable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
    ]
