# Generated by Django 5.1.2 on 2024-12-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0017_alter_logintable_user_type_amalgamationgallerytable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('RESTOURANT', 'restaurant'), ('TOURIST', 'tourist'), ('USER', 'user'), ('RESORT', 'resort')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PhotoShootGalleryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('SHOOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.photoshoottable')),
            ],
        ),
        migrations.CreateModel(
            name='RatingReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(blank=True, max_length=30, null=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
    ]
