# Generated by Django 5.1.2 on 2024-12-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportComApp', '0018_alter_logintable_user_type_photoshootgallerytable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('USER', 'user'), ('RESTOURANT', 'restaurant'), ('ADMIN', 'admin'), ('RESORT', 'resort'), ('TOURIST', 'tourist')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AmalgamationRatingReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('AMALGAMATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.amalgamationtable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRatingReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('PARKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.parkingspottable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPointRatingReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('POINT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.viewpointtable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportComApp.usertable')),
            ],
        ),
        migrations.DeleteModel(
            name='RatingReviewTable',
        ),
    ]
